apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "registry-gate.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry-gate.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.storage.className }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
